### ISSUE TITLE
Standalone Podlove Webplayer not showing up

### ISSUE THREAD

**Issue by haslinger** [podlove/podlove-ui#1021]
First off: Thanks for your hard work, greetings and best wishes from the Panoptikum-Guy in Vienna!

I'm trying to update the Webplayer within Panoptikum to the latest version and installed 5.7.4 via npm. Copied the assets into the staticly served file structure, that now looks like [this](https://code.informatom.com/Panoptikum/pan/src/branch/main/priv/static/web-player). 

Updated the config to v5-structure and see assets beeing loaded Status 200 by embed.js (so all fine, I guess): 

![loaded](https://user-images.githubusercontent.com/1116624/147754806-c17b0ee3-34d3-4f5c-8c7a-f49b38b37228.png)

But the player itself doesn't show up and nothing helpfull in the Firefox console. 

But in Chrome I get error messages:
![console](https://user-images.githubusercontent.com/1116624/147755115-e3dc89a1-713d-4c9d-bbf9-7e0b5a6bca67.png)

Searching for that iFrameSizer in the code, I see links to ../../node_modules/iframe-resizer/index.js, 
a directory structure we don't have in the npm package files.
[The npm web-player page](https://www.npmjs.com/package/@podlove/web-player) says there are no external dependencies. 

Am I missing something here? Any tipps highly appreciated.

**Comment by alexander-heimbuch** [comment]
Hey Stefan,
can you share a reproducable example so I can debug it? The Mainfest error looks strange.

**Comment by haslinger** [comment]
Creating the extracted example everything works fine. So, thanks for your help! 
I now know, that my environment around the player somehow disturbs it, but I also know, that my config of the player itself is fine.
It could be something with the Phoenix LiveView js-library interfering with it. I will investigate that and come back later here to report.

**Comment by haslinger** [comment]
As expected in my closing comment above, I screwed up the proper loading event.

If somebody ever searches  here for a Phoenix LiveView (or Surface) integration, mounted is the right event, e.g. Hook for a Surface Component:

```
import podlovePlayer from "../../../priv/static/web-player/embed.js"

let PodlovePlayer = {
  mounted(){
    window.podlovePlayer("#podlove-player", episode, config);
  }
};

export {PodlovePlayer};
```

The full source code for a Surface Component can be found [here](https://code.informatom.com/Panoptikum/pan/src/branch/main/lib/pan_web/live/episode/podlove_player.ex).

Cheers, thanks, and sorry for the noise!
