### ISSUE TITLE
Podlove Webplayer: Iframe-Höhe passt sich verzögert an Viewport Resize an

### ISSUE THREAD

**Issue by mgschoen** [podlove/podlove-ui#1029]
###  Ausgangssituation

Podlove Webplayer via `window.podloveWebplayer` in einer responsiven Seite eingebunden.

### Beschreibung

Bei Änderung der Viewport-Breite, die zum Umspringen auf einen anderen Breakpoint im Player-Layout führt, passt sich die Höhe des einbindenden `iframe` nicht an die neue Player-Darstellung an. Erst wenn eine weitere Interaktion stattfindet, wird auch die Höhe korrekt angepasst. Beispiel für fehlerhafte Darstellung:

![Bildschirmfoto 2022-01-18 um 11 39 45](https://user-images.githubusercontent.com/22660469/149923866-4dc0bb20-000d-4e0c-926f-3e2121a363bd.png)

Die Änderung der Viewport-Breite kann z.B. durch den Wechsel Porträt/Landscape auf Mobilgeräten erfolgen, aber auch durch größer/kleiner Ziehen des Desktop-Browsers.

Beobachtete Interaktionen, die die Höhenanpassung anschießend triggern:

- ein weiteres Resize
- Klick oder Touch Interaktion mit dem Player
- Scrollen der Parent-Seite

Der Fehler tritt **nicht** auf während ein Audio wiedergegeben wird.

### Reproduktion

Zum Beispiel hier: https://podlove-webplayer-resize.surge.sh/ 

Beobachtet auf folgenden Geräten:

- iPhone Safari mit iOS 15
- Chrome 97
- Firefox 91

**Comment by alexander-heimbuch** [comment]
Ich habs versucht nachzustellen aber so richtig konnte ich es nicht reproduzieren. Vermutlich ist das ein Bug im [iframeResizer](https://github.com/davidjbradshaw/iframe-resizer). Ich kann gerne den upgraden und schauen ob es das Problem behebt.

**Comment by mgschoen** [comment]
Moin @alexander-heimbuch , danke für die schnelle Antwort. Ich habe es hier noch mal beispielhaft im Video nachgestellt, damit es leichter nachvollziehbar ist:

https://user-images.githubusercontent.com/22660469/150101185-60d1bb17-a616-4da6-af78-022e1ae03d7c.mov

Probiere das gerne mal aus, ich kann damit dann auch gerne noch mal testen. Danke und Grüße!

**Comment by alexander-heimbuch** [comment]
Hey @mgschoen ich hab den Grund gefunden. Durch die transition konnte der iframe resizer nicht die korrekte Größe berechnen. Ich nehme die Transition raus. #1034

**Comment by mgschoen** [comment]
Good news @alexander-heimbuch, vielen Dank! Gib gerne Bescheid, wenn ich testen soll, ansonsten freue ich mich auf die nächste Version 🎉
