### ISSUE TITLE
API for requesting play not working

### ISSUE THREAD

**Issue by MarcinPiniarskiDS** [podlove/podlove-ui#1030]
According to Podlove documentation, the only way to force autoplay is using runtime API (https://docs.podlove.org/podlove-web-player/v5/extensions/runtime-api).
One should call `store.dispatch({type: 'PLAYER_REQUEST_PLAY'});` e.g. like this:
```
window.podlovePlayer("#app", episode, config).then((store) => {
  store.dispatch({ type: "PLAYER_REQUEST_PLAY" });
});
```

Unfortunately, dispatch this event does not work - there is no effect. 

I’ve tested it a lot, trying to make it work. Other events (like ‘PLAYER_MUTE’) do work as expected. I’ve tried to dispatch 'PLAYER_REQUEST_PLAY' after a timeout and even “manually” dispatching a click event on #play-button--play.

Surprisingly, if a user clicks or any Podlove Player area before an event is dispatched then this event does have an expected effect. Seems like there is some connection between the implementation of this event and dispatching it as a result / after a user action.

**Comment by alexander-heimbuch** [comment]
That is because Browsers require a user interaction before requesting audio or video to play, which is nice if you want to limit the ability of unwanted auto playback but a bummer for this use case ☹️Unfortunately not much that I can do about but worthwhile a mention in the docs.

**Comment by MarcinPiniarskiDS** [comment]
I see. Thank you for your response.

**Comment by alexander-heimbuch** [comment]
Added a note in the documentation: https://docs.podlove.org/podlove-web-player/v5/extensions/runtime-api#caveats
