### ISSUE TITLE
Too much whitespace below emedded player (on .wrapper)

### ISSUE THREAD

**Issue by jnns** [podlove/podlove-ui#104]
As you can see in the image below, there's a white area of roughly 20px below the embedded player. It is whitespace that is part of the iframe's content - not from the surrounding template. It often goes unnoticed when the website's background is white itself.

![grafik](https://user-images.githubusercontent.com/206281/61872677-45e62d00-aee4-11e9-96bc-c01f1496b131.png)

Removing `min-height: 250px;` from the `.wrapper` directives resolves this problem (at least at first glance).
![grafik](https://user-images.githubusercontent.com/206281/61873044-32879180-aee5-11e9-952b-dcc158717752.png)

![Bildschirmfoto von 2019-07-25 14-05-20](https://user-images.githubusercontent.com/206281/61873098-5cd94f00-aee5-11e9-9eca-f508df8d8513.png)

**Comment by alexander-heimbuch** [comment]
this bug is already tracked here: #104
