### ISSUE TITLE
Podlove Web Player: Iframe-Embeds don't show full player and throw error

### ISSUE THREAD

**Issue by herzogmedia** [podlove/podlove-ui#1041]
When embedding the podlove web player into another site using an iframe, the following behaviour ocurrs:

### Current behavior

- shows only title, episode image, timeline and play button
- does not respond to height changes
- thows type-error
```
Uncaught (in promise) TypeError: e.features is undefined
ao https://podcast.campustv-mainz.de/wp-content/plugins/podlove-web-player/web-player/share.js:2
 ```

### Expected Behaviour

- show full player as configured (including tabs, full player controls, etc.)
- respond to height changes

### Environment

- Podlove Web Player 5.4.15 (Wordpress-Plugin, hosted locally)
- Podlove Publisher 3.8.0
- Wordpress 5.9.0

Demo: https://hype.campustv-mainz.de/#portfolio

**Comment by knoxmic** [comment]
Hey Lukas, when embedding as iFrame/share, the XL-template (full player) including tabs is not used.

https://github.com/podlove/podlove-ui/blob/development/apps/web-player/src/player/share.mustache#L37

Unfortunately I can't help you with the JavaScript error.

**Comment by herzogmedia** [comment]
Hey, thanks for the heads up. That is unfortunate. And the iframe-template does not seem to be customizable...

**Comment by alexander-heimbuch** [comment]
Hey @herzogmedia,
I couldn't reproduce the error on a test embed. Customisation for the embed template is not possible since the requirements are very high due to the limitations of the iframe.
