### ISSUE TITLE
Player does not find mp3 file, possible through chapter images

### ISSUE THREAD

**Issue by krlng** [podlove/podlove-ui#1058]
Hello,

I currently can not make the PodLove Player run my most recent podcast episode. To me the mp3 file looks just fine and it was produced using auphonic with the same workflow that created my last 20 episodes. Also the duration detection works correctly. 

The only thing that might cause the issue are chapter images, as I used those for the first time in this episode. Are there any known problems with mp3 files that contain chapter images?

Error message of the audio player:`The Player recieved an invalid configuration. Without media files the player can't be used. Please reach out to the host to fix this problem.`

The problematic file: https://techtiefen.de//wp-content/uploads/37_datenvisualisierung.mp3
Podlove podcast publisher version 3.8.1

**Comment by knoxmic** [comment]
Hey,

can you provide a test page with the player not playing the audio file?

As soon as the episode is online, you can also check the corresponding configuration for errors, for example: https://techtiefen.de/36-nlp/?podlove_action=pwp4_config

**Comment by krlng** [comment]
Okay, I simply published it: https://techtiefen.de/37-datenvisualisierung/?podlove_action=pwp4_config but I don't see any errors

**Comment by knoxmic** [comment]
Ok, the audio is empty 🤔

![image](https://user-images.githubusercontent.com/651018/162232023-1a8a8db9-7260-4765-8906-b39c07b1bb9d.png)

**Comment by krlng** [comment]
Okay, that does make sense, but the question then is, why is it empty? This is, what it looks like in the admin ui:

![Screenshot 2022-04-07 at 17 18 08](https://user-images.githubusercontent.com/1107509/162233718-58b94bf4-ac2a-43c5-afed-fea24eb700bb.png)

Also it opens the correct path, when I click on the episode.

**Comment by knoxmic** [comment]
At this point the code tries to get the HTTP response headers of the file (url) using `curl`, apparently this fails at the moment. Maybe something was changed on the server? Can you check the correct function of `curl` via the console at the server? 

Does it work for `curl -I 'https://techtiefen.de/wp-content/uploads/37_datenvisualisierung.mp3'`?

Maybe you can find more tips here: https://community.podlove.org/search?expanded=true&q=file%20not%20found

**Comment by krlng** [comment]
Thanks very much, I found the issue. I run my wordpress installation in a docker container and from that I was not able to fulfill the curl without certification error. The reason where outdates SSL base certificates, after upgrading those and a container restart it is working again. Thanks a lot.
