### ISSUE TITLE
File download is a redirect in the same tab

### ISSUE THREAD

**Issue by fliiiix** [podlove/podlove-ui#1096]
If you use the download mp3 for example on the https://podlove.github.io/podlove-web-player/v5/playground/
It does not start a download it plays the mp3 in the iframe and looks like this

![image](https://user-images.githubusercontent.com/1682954/198883964-020fae2a-76f4-4d89-9aee-bd9972e702da.png)

Not sure why it does not work as the `download` attribute seems to be set.

**Comment by alexander-heimbuch** [comment]
This is not an issue with the Player itself it is more related to the server configuration. It is such a common issue that we have a dedicated video just to explain it :D https://community.podlove.org/t/podlove-publisher-how-to-enable-force-downloads-fix-mime-types/78
