### ISSUE TITLE
Edge/IE11: Unable to get property 'dispatch' of undefined or null reference

### ISSUE THREAD

**Issue by gerritvanaaken** [podlove/podlove-ui#111]
Standalone version, embed manually/locally: I get three lines of error message in IE11 and older Edge versions (before the Chromium switch), when the player gets initialized. The player does not load. Firefox, Safari and Chrome is working fine. Latest release 4.1.6. Live URL: 

https://lu-web.de/lu-web-videos/lu-audio/audio-lu-umfrage-fas/

<img width="998" alt="Bildschirmfoto 2019-08-27 um 14 13 13" src="https://user-images.githubusercontent.com/227735/63770170-d6919d80-c8d4-11e9-8e04-78f331d90125.png">

**Comment by alexander-heimbuch** [comment]
In general IE11 is not supported. Can you try the 4.5.10 (https://www.npmjs.com/package/@podlove/web-player) Version to test interoperability with Edge?

**Comment by gerritvanaaken** [comment]
After embedding the player properly, it works in older Edge versions. I use a simple audio Element as a fallback for IE now.
