### ISSUE TITLE
WP Webplayer subscribe language

### ISSUE THREAD

**Issue by Hibbou** [podlove/podlove-ui#1112]
When browsers default language is not supported (example fi) player is displayed in english, as it should.
But when +subscribe button is pressed everything subscribe related is in german (Abonnieren bei) etc.
installed plugin versions:
           - Podlove Podcast Publisher v3.8.2
           - Podlove Web Player v5.7.1

**Comment by alexander-heimbuch** [comment]
Thanks for the report!

**Comment by alexander-heimbuch** [comment]
Should be fixed with v5.12.1
