### ISSUE TITLE
Disable iFrameResizer log or make it configurable

### ISSUE THREAD

**Issue by dantio** [podlove/podlove-ui#1116]
iFrameResizer logs lots of messages in the console. In prod build this is not required. Please disable it or make it configurable.

![image](https://user-images.githubusercontent.com/1328163/223102491-14509a51-63ee-4f9a-b714-c986a961fa9e.png)

https://github.com/podlove/podlove-ui/blob/b590e747339ed3e6a41427cb3bc08ff48d5998bc/apps/web-player/src/player/index.js#LL50C14-L50C14

**Comment by alexander-heimbuch** [comment]
Should be fixed with v5.12.1
