### ISSUE TITLE
Tab title border color can't be changed

### ISSUE THREAD

**Issue by zichy** [podlove/podlove-ui#1118]
The border underneath the player title does not have a custom color, it's always gray (`border-gray-400`):

https://github.com/podlove/podlove-ui/blob/b590e747339ed3e6a41427cb3bc08ff48d5998bc/apps/player/src/components/tab-title/TabTitle.vue#L16

Depending on your background color, this may result in a very bad contrast:

<img width="428" src="https://user-images.githubusercontent.com/173749/232544872-d4aa48a6-6c36-4f95-a4c2-00594f3cdc05.png">

Could the border color please be defined by the custom player colors? 🙏

**Comment by alexander-heimbuch** [comment]
Should be fixed with v5.12.1
