### ISSUE TITLE
New Features? (with templates for suggestion)

### ISSUE THREAD

**Issue by lfalipou** [podlove/podlove-ui#114]
Hi @alexander-heimbuch and @timpritlove!

I'm new here. First, I'd like to congratulate you: you really did a fantastic job with the Podlove Web Player!

I came across Podlove because I was looking an audio player that could handle dynamic transcript.

I'd love to use it on my future website where I'll teach French.

If you are open to suggestions of new features, I have some but as I've not yet had the opportunity to install your player, I apologize in advance if some of my suggested features are already available.

---

**Here are my suggestions :**

--

**FOR THE PODCAST LISTENER**

> The most significant improvement would be to have the option to put the player in fullscreen for not being distracted by anything else on the page.

I spent some time creating every template (INFOS, CHAPTERS, TRANSCRIPT...) to show you how it could look like (I tried to stay as close as possible of the current design).

![computer_fullscreen](https://user-images.githubusercontent.com/10856895/66547798-518adc80-eb40-11e9-98d9-02aec5c31c93.png)

[Podlove_fullscreen_on_a_computer.pdf](https://github.com/podlove/podlove-ui/files/3710945/Podlove_fullscreen_on_a_computer.pdf)

.

![mobile_fullscreen](https://user-images.githubusercontent.com/10856895/66547811-5780bd80-eb40-11e9-8e90-7d6a07a90dbc.png)

[Podlove_fullscreen_on_a_mobile_phone.pdf](https://github.com/podlove/podlove-ui/files/3710947/Podlove_fullscreen_on_a_mobile_phone.pdf)

--

**FOR THE PODCAST CREATOR**

**In the Player Controls area:**

> P1. to customize the number of seconds to play backward and forward (by default 15 and 30).

> P2. to remove the name of the chapter below the PLAY button.

**In the Transcript window:**

> T1. to add transcripts in other languages (= subtitles) than the one used for the audio (also VTT synched) and to switch from one to another with just one click (see my templates in the PDFs above).

> T2. to customize the text "Chapter 1", "Chapter 2"... (unless it is already possible).

> T3. to have a text editor to be able to:
	- change the size, font and color of the text,
	- put the text in bold, italic...
	- change the line space,
	- make line breaks,
	- skip lines,
	- add bullet points
	- ...
Reading would be more appealing.

> T4. to remove the "Search" and "FOLLOW" components.

> T5. to display text without having to (always) precede it with someone's name (such as Tim Pritlove). In my case, I'd like to use Podlove to tell a story with dialogues AND narration.
A typical snippet of text would be:

	[Narration]

	CHARACTER 1
	{blah blah blah}

	CHARACTER 2
	{blah blah blah}

	[Narration]

> T6. to remove the left and right arrows used to switch from one chapter to another.

> T7. to add "hotspots" in the text that would pause the audio and open a picture or an embedded video in fullscreen mode.

**In the Chapters window:**

> C1. to customize the word "CHAPTERS" (unless it is already possible).

> C2. to name the chapters in different languages and easily switch from one language to another (> see T1 above).

**Bug:**

> When I use your demo player on my computer with Chrome, the cursor of the scroll bar ends up disappearing at the bottom right of the window when I scroll a lot (even if there is still a lot of text to display).

![bug](https://user-images.githubusercontent.com/10856895/66545833-de7f6700-eb3b-11e9-982c-5e86c62b84fb.gif)

I hope you will share my enthusiasm for these improvements and long life to Podlove!

Laurent

**Comment by alexander-heimbuch** [comment]
Hey,
thanks for the all the nice feedback :) Since I'm working on the next player iteration some of your feedback might be already resolved. The biggest change will be a template engine that can be used to create custom players. I'm looking forward for a "real" full screen template and your feedback on the customisation abilities :) I will keep this thread updated once the feature branch was merged.

**Comment by lfalipou** [comment]
Hi @alexander-heimbuch, it looks like my answer was deleted so I'm not sure whether you saw it or not.

I was asking you to be more specific when you say:

> I'm looking forward for a "real" full screen template and your feedback on the customisation abilities

What do you mean by "real"? Was the one that I sent you not suitable?
Let me know what I can do and I'll do my best to help.

Laurent

**Comment by alexander-heimbuch** [comment]
I was referring to the new player ability to use custom templates. So you could realise your fullscreen template with that new functionality. I'm working on a documentation that should shed some more light onto the new player features. In the meantime you could have a look at a working prototype: http://podlove-player-next.surge.sh/

**Comment by lfalipou** [comment]
Hi @alexander-heimbuch,

First I'd like to say a huge thanks for the early access to the demo! :-)

I spent a few hours hours playing with it and thinking about each and everything thing that would be nice to customize and I summarized it in the PDF file attached.

[My feedback](https://github.com/podlove/podlove-ui/files/3774947/NEW_Podlove_Player.pdf)

I should clarify that I didn't make any comment about the fullscreen mode because I'd rather wait to read your documentation (but if you want to offer us the option to go in fullscreen mode, I guess the player will need some adjustment of the design to free some space for the fullscreen icon, depending where you want to put it).

Let me know what you think about it.

**Comment by alexander-heimbuch** [comment]
Wow that's a very comprehensive feedback 👍 I will feed it to our designers to evaluate the feedback. To tackle the discovered bugs I will start to track them separately in the Player 5 project.

**Comment by lfalipou** [comment]
Thanks for your kuddos. 
I tried to male it digestible.

Feel free to put me in touch with your webdesigners as I'd love to invest myself in the Podlove project (I could help for UX, bug tracking and suggestion of new features as you may have noticed :-) ).

**Comment by lfalipou** [comment]
Hey @alexander-heimbuch, I hope you're doing well.
First, let me wish you all the best for this new year.

Now, while waiting for the version 5 of Podlove to be released, I tried to install the Podlove Publisher plugin to see how it works in the backend of WordPress.
Unfortunately, I was unable to test several features such related to the transcripts because:
- it doesn't show up even when I click on the checkbox to display the tab
- the plugin doesn't react correctly when I upload my .vtt file (it starts loading and ends up with nothing).

I guess you already know about that and I just wanted to ask if you have a release date for the new player and new Podlove Publisher plugin.

Thanks for all the hard work you do for us.
--
Laurent

**Comment by alexander-heimbuch** [comment]
The Podlove Web Player integration is done in the publisher repo: https://github.com/podlove/podlove-publisher So in order to contribute to the transcript topic I highly recommend to get in contact with @eteubert.

**Comment by lfalipou** [comment]
Thanks for your prompt answer, Alex.

I tried to reach out to Eric on the community forum but I think he's pretty busy right now because he hasn't been able to answer me lately.

Regarding the web player v5, do you know when il t will be supported by the WordPress plugin?

**Comment by alexander-heimbuch** [comment]
We are working on a dedicated plugin to decouple the publisher and the web-player release flows.

**Comment by lfalipou** [comment]
Okay. Thanks for the info. So it's up to me to be patient :-).

**Comment by alexander-heimbuch** [comment]
Podlove Web Player Plugin was released that should cover custom templating and theming.

**Comment by lfalipou** [comment]
Hi @alexander-heimbuch Alexander, sorry for missing your reply 2 and a half years ago (!). And congrats for where you brought the plugin!

Are you still in charge of the development of Podlove?

If so:
- I know this isn't necessarily something podcasters need, but if you're welcoming new use cases, can I ask if inserting "rich" content (such as images, YT videos, Google Maps...) into the transcript is something you might consider in the future?
- If so, could you also add an option (back office) to automatically stop the playback when the transcript reaches any "rich" content (it will then be up to the user to resume playback anytime)?

Best,

Laurent
