### ISSUE TITLE
PLAYER_INIT does not reset audio correctly, leading to multiple files playing simultaneously

### ISSUE THREAD

**Issue by Connum** [podlove/podlove-ui#145]
In order to reproduce the issue:

1. Visit https://docs.podlove.org/podlove-web-player/player-dispatches.html
2. Choose `PLAYER_INIT` from the dropdown and hit "dispatch"
3. Click the play button in the player or alternatively dispatach `PLAYER_REQUEST_PLAY`

The player will play the audio file two times in parallel with more or less delay between the two, resulting in an echo-like playback. If you hit "dispatch" multiple times in step 1, the number of parallel playbacks will increase accordingly and the time display will go haywire while trying to update according to all the different versions. If you dispatch `PLAYER_INIT` with different data from another podcast and restart playback, it will play both podcasts at the same time, despite updating the UI with the new data.

The background for my usecase is that I'm trying to implement a single player in the page that will play the episodes when you hit a play button. Everything works fine despite this issue with the player seemingly not resetting everything that needs to be reset on initialization, and rather appending the audio streams to the configuration instead.

**Comment by alexander-heimbuch** [comment]
What version are you using right now? I reworked the init flow in version 5 to support a playlist like functionality.

**Comment by Connum** [comment]
Whatever version is being used on https://docs.podlove.org/podlove-web-player/player-dispatches.html ;-) That should be `4.5.11`. I'm also using that in my site where I'm enountering the issue as well.

Is version 5 already avaiable somewhere?

**Comment by Connum** [comment]
Any news on this? I guess I'll meanwhile have to use a workaround using multiple players and showing/hiding them according to the currently playing episode, but it would be nice to truly have a single player in the future. It would work if only PLAYER_INIT would reset everything correctly.

**Comment by alexander-heimbuch** [comment]
Sorry for the late response. 5 is [currently available as a preview version](https://www.npmjs.com/package/@podlove/web-player) because the configuration might still be changed. You can already have a look at the upcoming documentation: http://amazing-sound.surge.sh

**Comment by Connum** [comment]
Thanks, I'll have a look at it! Are there any chances for a fix in version 4? Basically, there should only ever be one audio stream playing in parallel ever, right?

**Comment by alexander-heimbuch** [comment]
Not planned yet. I had to rework the core audio driver integration. It is very tricky to reset the audio but keep all event bindings alive without introducing another audio element.

**Comment by Connum** [comment]
I'll implement what I have in mind with multiple players via hiding/showing them accordingly, but I thought I'd let you know that `PLAYER_INIT` seems to still be broken in v5. http://amazing-sound.surge.sh/extensions.html 
1. Hit play
2. Optionally: Hit pause
3. Send `PLAYER_INIT`

If you hit pause before, you can now hit play and it will not play multiple streams in parallel, but jumping in time either by hitting one of the buttons (chapter or 15/30s)  or clicking on the timeline doesn't work anymore.

**Comment by alexander-heimbuch** [comment]
Thanks for the report. Seems like a regression since I had to implement custom behaviour for MS Edge support :/
