### ISSUE TITLE
Autoplay produces network error in Firefox

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-ui#258]
Autoplay doesn't work in some browsers because it requires a direct user interaction. For example: https://der-lautsprecher.de/ls019-hr2-der-tag-ein-gespraech-mit-florian-schwinn?autoplay=true

Suggested solution: the player shouldn't throw an error and simply ignore the autoplay request.

**Comment by andreashouben** [comment]
To reproduce: Add ?autoplay=true to the url of the page where the player is embedded.
