### ISSUE TITLE
Clicking into the timeline of a track wont start at the time of the label.

### ISSUE THREAD

**Issue by fno** [podlove/podlove-ui#301]
Hey i just observed a reoccurring bug in multiple different installations of the Podlove Web Player

Reproducible in Chrome & Firefox latest Versions on macOS and Windows 10 (both fully updated):

Expected behaviour: When i hover over the track timeline a time is displayed (e.g. 34:06) when i click on it it takes me to 34:06 of the track in the player

Observed behaviour:   When i hover over the track timeline a time is displayed (e.g. 34:06) when i click on it it takes me to a different time in the track that is somewhere near (deviation maximum was roughly 2 minutes). But never the exact moment that was labeled before. Tested with several Podlove Web Player installations and several hosted files each multiple times.This behaviour happens exlusively.

This doesnt seem to be related to versions or specific files.

**Comment by alexander-heimbuch** [comment]
Can you share some details to the used Audio format? We discovered this behavior with MP3 files with dynamic bitrates.

**Comment by fno** [comment]
Hey i stumbled on this mostly as a user of the player but i just downloaded a file that this happens to:
avinfo output is:

`File type ID:   MPG3
Num Tracks:     1
----
Data format:     1 ch,  44100 Hz, '.mp3' (0x00000000) 0 bits/channel, 0 bytes/packet, 1152 frames/packet, 0 bytes/frame
                no channel layout.
estimated duration: 9844.924100 sec
audio bytes: 98449241
audio packets: 376877
bit rate: 80000 bits per second
packet size upper bound: 1052
maximum packet size: 262
audio data file offset: 61170
optimized
audio 434160693 valid frames + 576 priming + 1035 remainder = 434162304`

if i can help you further im glad to do this but i'm not an expert on audio encoding

**Comment by alexander-heimbuch** [comment]
Can you share me a link so I can have an example to debug?

**Comment by fno** [comment]
https://raumzeit-podcast.de/2019/12/20/rz082-bodenerkundung-auf-dem-mars/

**Comment by alexander-heimbuch** [comment]
Can you specify what you mean with "preview label"?

**Comment by fno** [comment]
the label on the left side of the timeline. it displays the current time while playing but is replaced by the "time under mouse cursor"-time while hovering over the timeline.
