### ISSUE TITLE
PLAYER_UPDATE_PLAYTIME no longer working

### ISSUE THREAD

**Issue by Connum** [podlove/podlove-ui#329]
Similar to #145, PLAYER_UPDATE_PLAYTIME seems to bo no longer working.

In order to reproduce the issue:
1. Visit https://docs.podlove.org/podlove-web-player/player-dispatches.html
2. Choose PLAYER_UPDATE_PLAYTIME from the dropdown and hit "dispatch"

It doesn't jump to the position given in the payload (I also tried 0 and 1, which should jump to the beginning), no matter if the player is currently playing or not.

It's also not working in the version 5 preview at http://amazing-sound.surge.sh/extensions.html

Is there a workaround to this until it gets fixed? The chapters still work, so the player seems to be able to jump internally, just not via the dispatch API.

**Comment by alexander-heimbuch** [comment]
`PLAYER_UPDATE_PLAYTIME` is dispatched by the media backend. In order to request a given playtime you should use `PLAYER_REQUEST_PLAYTIME`. Still the documentation is confusing and I will need to clarify this more prominently :/
