### ISSUE TITLE
Contributors' role and group use.

### ISSUE THREAD

**Issue by AhoyLemon** [podlove/podlove-ui#33]
Hey all,

Just found out about this project and I think it's a really great web player, currently working on implementing it into my own site. In doing so though, I noticed the `role` and `group` fields, neither of which seem to be getting used, as far as I can tell.

Using an example from the documentation...

```
{
      "name": "Tim Pritlove",
      "avatar": "https://freakshow.fm/wp-content/cache/podlove/47/08928e3c26dcb1141d67ad75869619/tim-pritlove_150x150.jpg",
      "role": {
        "id": "9",
        "slug": "team",
        "title": "Team"
      },
      "group": {
        "id": "1",
        "slug": "onair",
        "title": "On Air"
      },
      "comment": null,
      "id": "tim-pritlove"
    },
    {
      "name": "Rainer",
      "avatar": "https://freakshow.fm/wp-content/cache/podlove/e3/0e1625d65c32720b76624262bfdc59/rainer_150x150.jpg",
      "role": {
        "id": "7",
        "slug": "composition",
        "title": "Komposition"
      },
      "group": {
        "id": "3",
        "slug": "support",
        "title": "Support"
      },
      "comment": null,
      "id": null
    },
}
```
this data gives me this result:
![image](https://user-images.githubusercontent.com/3413200/55899126-b1043180-5b89-11e9-9d15-31af9ed58efe.png)

However, from that data, I would expect something more like this:

![image](https://user-images.githubusercontent.com/3413200/55899526-9bdbd280-5b8a-11e9-94f3-f0256932da99.png)

Am I misunderstanding the inteintion here? Or are these fields (as well as `comment` and `id` and `slug`) unused?

**Comment by milgner** [comment]
Just stumbled over this and saw that @andreashouben (:wave:) and others worked on this not that long ago - nice! Is it still WIP or are you planning to create a PR for this?

**Comment by alexander-heimbuch** [comment]
It is already in the Podlove 5 Beta Player :) https://github.com/podlove/podlove-ui/blob/development/apps/player/src/components/tab-shownotes/TabShownotes.vue I should close this issue :P

**Comment by milgner** [comment]
Fantastic, thanks to all involved! I'll give the beta version a spin then 👍
