### ISSUE TITLE
Subscriptions for download and share events

### ISSUE THREAD

**Issue by AhoyLemon** [podlove/podlove-ui#34]
As I look into the subscriptions for the web player, I see a bunch of things I can do with the switching of tabs and streaming of audio. but there's no subscriptions on anything inside of either the Download or Share buttons. 

I'm tracking play actions like this....

```javascript
podlovePlayer('#PodLovePlayer', options).then(function (store) {
      store.subscribe(() => {
        const { lastAction } = store.getState()
        if (lastAction.type == "PLAY") {
          trackEvent("listen", "play", window.location.pathname);
        }
      });
    });
```

...and I'd love to be able to extend that out with something like this...
```javascript
podlovePlayer('#PodLovePlayer', options).then(function (store) {
      store.subscribe(() => {
        const { lastAction } = store.getState()
        if (lastAction.type == "PLAY") {
          trackEvent("listen", "play", window.location.pathname);
        } else if (lastAction.type == "DOWNLOAD") {
          trackEvent("download", lastAction.payload.src, window.location.pathname);
        } else if (lastAction.type == "SHARE") {
          trackEvent("download", lastAction.payload.network, window.location.pathname);
        }
      });
    });
```

does that make sense?

**Comment by milgner** [comment]
This might be possible already, as I just realized that the download link dispatches a `selectFile` event:

https://github.com/podlove/podlove-ui/blob/c898bae9c8bf04a08b127bd716f9c08c52a795c2/apps/player/src/components/tab-files/components/File.vue#L100

**Comment by alexander-heimbuch** [comment]
Yes I think I added that intentionally but didn't closed the ticket 😬
