### ISSUE TITLE
Google Podcast Linking doesn´t work

### ISSUE THREAD

**Issue by benhartwich** [podlove/podlove-ui#492]
Hi,

it´s not really clear, how to link google podcast: wether the full url nor the string after feed= does work to link to the google podcast. It seems that a random string is generated.

**Comment by alexander-heimbuch** [comment]
Hey,
you should pass in the feed, see https://github.com/podlove/podlove-ui/blob/development/packages/clients/src/google-podcasts/index.js#L15

I will add some documentation around this.
