### ISSUE TITLE
Theming is broken?

### ISSUE THREAD

**Issue by fliiiix** [podlove/podlove-ui#494]
I either don't understand how the theming works or it is broken

I used one of the official codesandbox and changed all colors to `fff`
https://codesandbox.io/s/player-configuration-kcmjr?file=/fixtures/config.json:121-122

And it still looks very green:
![image](https://user-images.githubusercontent.com/1682954/82732039-08704d00-9d0b-11ea-83e3-250d8e2b4197.png)

**Comment by alexander-heimbuch** [comment]
You might want to have a look at this file :D https://codesandbox.io/s/player-configuration-kcmjr?file=/example/config.js

**Comment by fliiiix** [comment]
I see :tada: Thanks!
Amazing how things work if you do them correctly.
