### ISSUE TITLE
Allow switching themes

### ISSUE THREAD

**Issue by drallgood** [podlove/podlove-ui#508]
Currently it doesn't seem to be possible to switch the theme at runtime, e.g. to switch from dark to light mode.

Not sure if I'm doing it wrong, but even setting the theme in the store doesn't work.

**Comment by alexander-heimbuch** [comment]
It is possible if you are using this action:
`
store.dispatch({
  type: "SET_THEME",
  payload: {
    version: 5,
    theme: {
      tokens: {
        brand: "#E64415",
        brandDark: "#235973",
        brandDarkest: "#1A3A4A",
        brandLightest: "#E9F1F5",
        shadeDark: "#807E7C",
        shadeBase: "#807E7C",
        contrast: "#000",
        alt: "#fff",
      },
    },
  },
});
`

**Comment by drallgood** [comment]
Tried that, but it doesn't update the player.

Here's my code:
```
window.addEventListener('storage', function(e) {  
                        if(e.key == 'colorMode') {
                          window.podloveStore.dispatch({
                            type: "SET_THEME",
                            payload: {
                              version: 5,
                              theme: {
                                tokens: (e.newValue == 'lit')? litConfig:darkConfig
                              }
                            }
                          });
    }
});
```

**Comment by drallgood** [comment]
Got it. The type is "PLAYER_SET_THEME" :)

Might be nice if you could document that!

**Comment by alexander-heimbuch** [comment]
Yes you are right :D, I'm using a autoprefixer function internally. Btw. if you have some kind of bundler available you could directly use the player-actions package: https://www.npmjs.com/package/@podlove/player-actions
