### ISSUE TITLE
Embed podlove webplayeron static page

### ISSUE THREAD

**Issue by swschilke** [podlove/podlove-ui#538]
Hi, is it enough to include embed.js to use the webplayer in a webpage (incl. the necessary json file naturally)? It's not in a node environment, more static pages.

Kind regards

.

**Comment by alexander-heimbuch** [comment]
Yes that is absolutely sufficient. There is no node environment required. Have a look at the documentation to see how it's done: https://docs.podlove.org/podlove-web-player/
