### ISSUE TITLE
German translations not working

### ISSUE THREAD

**Issue by michaeljakob** [podlove/podlove-ui#574]
How do you force the podcast player (wordpress plugin) to use German as language?

How do I use the files at `https://github.com/podlove/podlove-ui/blob/development/apps/player/lang/de.json` ?

Podcast Player always shows English text like "Chapters", see the screenshot below:
<img width="973" alt="Screenshot 2020-07-13 22 24 53" src="https://user-images.githubusercontent.com/3597595/87350130-ff249380-c589-11ea-9985-413b5456188d.png">

**Comment by alexander-heimbuch** [comment]
The player is browser locale sensitive. If you have configured english as your preferred browser locale you see all of the controls and labels in english. If you switch to german, you will get german controls and labels.
