### ISSUE TITLE
Copy URL note is white on white

### ISSUE THREAD

**Issue by Inrumpo** [podlove/podlove-ui#592]
The (new) Podlove Subscribe Button introduced with the Player 5 lets users select a variety of podcast services. They open up in a new tab. In the meantime, the existing tab will display this message (not for all services though):

![PSB note white on white](https://user-images.githubusercontent.com/11300164/88456601-06e41200-ce7f-11ea-807c-6a58977d60be.png)

The RSS-feed URL is white on white and therefore invisible. 

![PSB note marked](https://user-images.githubusercontent.com/11300164/88456608-267b3a80-ce7f-11ea-8fbf-61881d06d052.png)

I've tested this on:

- Up to date Windows 10 with Chrome and Brave browsers
- iOS 13.5.1 Brave browser app and Safari app

**Comment by Inrumpo** [comment]
The latest version of the player (5.3.1) and/or the publisher (3.1.0) plugin does fix the example posted in my original comment. Thanks!

Not all of them are fixed though.
![image](https://user-images.githubusercontent.com/11300164/98452983-a8ece900-2154-11eb-915a-e74ec08c3f87.png)

![image](https://user-images.githubusercontent.com/11300164/98452996-b6a26e80-2154-11eb-8eea-aa6aae1285d9.png)

(This example is from clicking Podscout on a Win10 desktop machine.)

**Comment by alexander-heimbuch** [comment]
argh :D Thanks for the report 👍
