### ISSUE TITLE
Volume bar is not customizable

### ISSUE THREAD

**Issue by alexander-heimbuch** [podlove/podlove-ui#653]
![](https://community.podlove.org/uploads/podlove/original/2X/d/dbaa59ca49a4ed0eef2c3fa467a0594085bb24a7.png)

![](https://community.podlove.org/uploads/podlove/original/2X/5/52ce07f7d188abe2c1534c18ee174321ae8411b3.png)

**Comment by dnkbln** [comment]
Hallo Alex, dies sieht evtl nach einem Einsteiger-Bug aus. Oder täusche ich mich? Ich würde mich mal daran versuchen. Willst Du eine weitere Farbe hinzufügen oder soll eine bestehende Farbe verwendet werden?

**Comment by alexander-heimbuch** [comment]
Moin Dirk,
sehr gerne! Ich würde vorschlagen die gleiche Farbe wie die Progressbar zu verwenden. Da das recht tief in den ui-components abgehandelt wird ping mich bei Fragen gerne an!

**Comment by dnkbln** [comment]
Hallo Alex, ich habe mal einen Pull-Request eingereicht. Ich bin nicht ganz zufrieden. Du hast es in der Progressbar genau anderes herum gelöst. Schau es dir mal bei Gelegenheit an.
