### ISSUE TITLE
Binding theme colors to templates

### ISSUE THREAD

**Issue by pgerstbach** [podlove/podlove-ui#671]
Hi,
I am having issues in finding working colors to match our brand.
The color names "brand", "brand dark", "brand darkest" and so on, always create strange results. Since our brand color is very light, I'd prefer to change the text-color as well to give more contrast.
Maybe it would be easier to use names like "episode-title", "controls" instead of "brand" and such?

Is there a way to set specific colors using templates? I didn't find a documentation how these "template" system works.
Thanks you!

**Comment by alexander-heimbuch** [comment]
Hey,
thanks for the feedback. We are aware that the current theming system doesn't fit all needs. Right now there is no plan to change the system. Looking forward I would really like to add support for CSS variables that would enable your described use case but would include a drop in browser support. If you are interested in some more detailed information lend an ear to this episode https://podlovers.org/episode/podlove-web-player/ (german content)

**Comment by pgerstbach** [comment]
Thanks! I look into the podcast episode! 👍
