### ISSUE TITLE
CSS Customization - Specifically the Outline of Focused Buttons

### ISSUE THREAD

**Issue by chrisspiegl** [podlove/podlove-ui#679]
Hi Everybody, I just found the Podlov Webplayer today while researching a beautiful and fully featured podcast player for my show.

Now, I started adding it into my 11ty.dev website setup, so far so good.

However, I noticed a small detail that kinda annoys me and I can't seem to figure out how to change it… maybe you can help, or it may be a feature request for the future. There are two points:

1) Since the player is in an iFrame it's not really possible to style it aside from the theme color settings and the templating options? Would it be possible to open the doors on that a bit more to add my own CSS file to the config for example?

2) With that, I specifically ran into the issue that the buttons for Chapter, Show Notes, Transcripts, and so on have a blue `outline: 5px auto -webkit-focus-ring-color1;` on the `button:focus` which is rather ugly to be honest and unnecessary for most things as far as I know.

Maybe this is specific to my browser (which is the Brave Browser)?

Now, I am open to hearing your thoughts. Looking forward to it.

Cheers,
Chris

**Comment by chrisspiegl** [comment]
Adding this image here. There are two borders kinda semi permanent. They stay even after the click has finished. But once I click outside of the iFrame or on Text inside the iFrame they disappear.

<img width="221" alt="Screen Shot 2020-10-13 at 09 55 20" src="https://user-images.githubusercontent.com/1096384/95832141-36960e00-0d3a-11eb-929c-16a55e90c042.png">

Probably something rather small, but I love details 🙈 and these two borders don't really look like they fit right…

**Comment by alexander-heimbuch** [comment]
I totally understand that this is struggling :D Feel free to open a PR and I will happily merge it 👍
