### ISSUE TITLE
Could not play when audio request meet 302 redirect

### ISSUE THREAD

**Issue by richshaw2015** [podlove/podlove-ui#736]
i.e. 
We have audio src `https://www.podtrac.com/pts/redirect.mp3/dovetail.prxu.org/188/204f2643-8ee9-487f-8266-abfb4a598e9f/619.mp3`
Will 302 redirected to `https://dovetail.thisamericanlife.org/188/NldaKbLwzFomkTHxLoGdMMIwgCBJyJyvgJxSXVBKq7g/619.mp3`

In this case, podlove player could not play (with no sound, in @podlove/player 5.3.1)

**Comment by alexander-heimbuch** [comment]
Hey,
could you point me to an instance to reproduce the issue? I tried that but for chrome, safari and firefox it worked out of the box.

**Comment by richshaw2015** [comment]
> Hey,
> could you point me to an instance to reproduce the issue? I tried that but for chrome, safari and firefox it worked out of the box.

i.e. Use the follow response, there is no sound; but if we replace url `https://www.podtrac.com/pts/redirect.mp3/dovetail.prxu.org/188/2e7d4179-ae80-4351-abf4-7fe5052e4c2a/218.mp3` with `https://dovetail.thisamericanlife.org/188/VxyFAG_kpRBTN_paxI46SuuKEf_V3G0YYULE2lOWEp0/218.mp3` (after 302 redirect), it's OK.

```json
{
  "version": 5,
  "show": {
    "title": "This American Life",
    "subtitle": "This American Life is a weekly public radio show, heard by 2.2 million people on more than 500 stations. Another 2.5 million people download the weekly podcast.",
    "poster": "https://files.thisamericanlife.org/sites/all/themes/thislife/img/tal-name-1400x1400.png",
    "link": "https://www.thisamericanlife.org"
  },
  "title": "Act V",
  "link": "http://feed.thisamericanlife.org/~r/talpodcast/~3/6g4pHYtlWxY/act-v",
  "publicationDate": 1605877198,
  "poster": "https://files.thisamericanlife.org/sites/all/themes/thislife/img/tal-name-1400x1400.png",
  "duration": "01:01:07",
  "audio": [
    {
      "url": "https://www.podtrac.com/pts/redirect.mp3/dovetail.prxu.org/188/2e7d4179-ae80-4351-abf4-7fe5052e4c2a/218.mp3",
      "mimeType": "audio/mpeg",
      "length": 0
    }
  ]
}
```
