### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by michaelrauh-web** [podlove/podlove-ui#737]
Hallo zusammen, 
setzt der Podlove Web Player Cookies? 
Hintergrund ist der, dass wir Podcasts auf unserem Nachrichtenportal per iFrame eingebunden haben und diese mit der CMP blocken wollen, wenn kein Consent vorhanden ist. 
Danke.

**Comment by alexander-heimbuch** [comment]
Hey Michael,

der Player setzt keine Cookies. Alle Informationen werden im local storage persistiert und nicht an den Server gesendet.
