### ISSUE TITLE
Fehler im Livestream?

### ISSUE THREAD

**Issue by ccanstein** [podlove/podlove-ui#747]
Beim Abspielen eines Livestreams (mp3) bleibt der Play-Button im Buffering-Status und wechselt nicht in den Playing-Status mit dem Pause-Icon.

Bug ?

Die Doku gibt zum Thema Livestream nichts weiteres her, außer dass der Player Livestreams unterstützt.

**Comment by alexander-heimbuch** [comment]
Sprichst du vom 4er oder 5er Player?

Der Player unterstützt abgeschlossene HLS Streams. Fortlaufende streams können zwar abgespielt werden, die Bedienelemente sind aber nicht darauf ausgelegt (negatives springen, live mode, ...). Das ist war alles theoretisch möglich wurde aber bisher aus mangelnden Bedarf nicht implementiert.

**Comment by ccanstein** [comment]
Moin! Danke für die schnelle Antwort. Es geht um den 5er. Könntest Du mir einmal per E-Mail schreiben (cc@elbsite.net), das wäre super! Es geht um eine größere Rundfunkanstalt ;)
