### ISSUE TITLE
[SB] - As a User i want to see feedback, when using copy feed button

### ISSUE THREAD

**Issue by Letty** [podlove/podlove-ui#77]

**Comment by Letty** [comment]
[how to copy text](http://www.javascriptkit.com/javatutors/copytoclipboard.shtml)

**Comment by alexander-heimbuch** [comment]
since this is hard to implement cross platform, I would suggest to simply use https://www.npmjs.com/package/copy-to-clipboard

**Comment by Letty** [comment]
The [implementation](https://github.com/sudodoki/copy-to-clipboard/blob/master/index.js) is mostly the same as in the example above.

**Comment by alexander-heimbuch** [comment]
I still would prefer to use a package that is dedicated to just this purpose and adds the needed abstraction + maintenance.
