### ISSUE TITLE
Podlove Player Embeds not working anymore

### ISSUE THREAD

**Issue by MaxZiebell** [podlove/podlove-ui#83]
The sharing is now broken again! Our partner using the iFrame embed is not seeing the player anymore! The version we have is Podlove Podcast Publisher 2.8.7 and the CDN Podlove Web Player. It now doesn't **suddently** render anymore.

See (right sidebar and error logs on that page):
https://integration.dosb.de/

Error logs are vast on the partner page… works on our page. We haven't changed anything?

<img width="1234" alt="20190624-69jli" src="https://user-images.githubusercontent.com/1752114/60008694-ce1eab80-9674-11e9-8fe5-e0190b9e9637.png">
<img width="663" alt="20190624-tt4ps" src="https://user-images.githubusercontent.com/1752114/60008740-e262a880-9674-11e9-8cfd-1a8ee11feb3d.png">
<img width="1221" alt="20190624-dcbks" src="https://user-images.githubusercontent.com/1752114/60008741-e262a880-9674-11e9-8357-4af8bb526226.png">

**Comment by alexander-heimbuch** [comment]
Release 4.5.7 is now released and will be distributed via CDN in the next hours
