### ISSUE TITLE
[Feature Request] Support for the new Podcast Index namespaces

### ISSUE THREAD

**Issue by Atreyu-94** [podlove/podlove-ui#883]
Do you plan to add support for this new namespaces? It is an alternative that aims to unify and standardize the feed.

There are many applications, hosts, and podcasts that already support it. 

In this way, the elements for: chapters, location, people, transliteration, etc. can be obtained directly from the feed.

The GitHub repository is this: 
https://github.com/Podcastindex-org/podcast-namespace

**Comment by alexander-heimbuch** [comment]
Hey,
not really sure how I might help with the podcastindex integeration. Any system could parse the feed and creates a compatible episode/config object. In the most cases this is the publisher but there are also other integrations available. We decided a loose coupling to the feed.

**Comment by alexander-heimbuch** [comment]
I will close this issue since I don't really understand the intend. Feel free to reopen it in case you want to follow up.
