### ISSUE TITLE
Add timed comments?

### ISSUE THREAD

**Issue by madix93** [podlove/podlove-ui#981]
Hi,

It would be great to be able to add comments timed to the exact moment we are listening to a podcast.

Fred.

**Comment by alexander-heimbuch** [comment]
Can you give me an example? Similar to what Soundcould is doing?

**Comment by madix93** [comment]
It could be similar to what Soundcloud is doing. I think adding a comment should pause the podcast to let time to write the comment.

**Comment by alexander-heimbuch** [comment]
There are a lot of questions involved to nail down such a feature. For example: what systems are involved to persist the comments? How would the API look like that the player should use? Should be a moderation function involved to account for unwanted comments? How are comments visualised?

If you could come up with a use case to justify the efforts we can work on a proper concept until then I will close the issue. Feel free to reopen the issue if you want to follow up on this topic :)
